### ISSUE TITLE
CT: lint error in ShaderTestUtils.ts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/alpenglow#8] opened 2023-12-22 15:31 UTC
On every cycle of CT:

```
alpenglow : lint
Lint failed with status code 1:
Running "lint" task

/data/share/phet/continuous-testing/ct-main/ct-snapshots/1703211243764/alpenglow/js/webgpu/tests/ShaderTestUtils.ts
21:1 error Promises must be awaited, end with a call to .catch, end with a call to .then with a rejection handler or be explicitly marked as ignored with the `void` operator @typescript-eslint/no-floating-promises

✖ 1 problem (1 error, 0 warnings)

Fatal error: Lint failed
Snapshot from 12/21/2023, 7:14:03 PM
```

**Comment by zepumph** [comment] 2023-12-22 21:37
I believe I actually caused this. Apologies.

**Comment by zepumph** [comment] 2023-12-22 22:06
Fixed on the most recent CT

**Comment by zepumph** [comment] 2023-12-22 22:07
Caused by the typescript conversion of Namespace over in https://github.com/phetsims/phet-core/issues/133

**Closed by zepumph** 2023-12-22 22:06 UTC
